AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::Batch::SchedulingPolicy resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.batch.schedulingpolicy.HandlerWrapper::handleRequest
      Runtime: java8
      CodeUri: ./target/aws-batch-schedulingpolicy-handler-1.0-SNAPSHOT-jar-with-dependencies.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.batch.schedulingpolicy.HandlerWrapper::testEntrypoint
      Runtime: java8
      CodeUri: ./target/aws-batch-schedulingpolicy-handler-1.0-SNAPSHOT-jar-with-dependencies.jar

